---
title: "Participation 10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise 10.1

```{r}
fibonacci <- numeric(10)
fibonacci[1] <- 1
fibonacci[2] <- 1
for (i in 3:10){
    fibonacci[i] <- fibonacci[i-2] + fibonacci[i-1]
 }
 fibonacci
```

## Exercise 10.2

```{r}
fibonacci <- function(len){
    if (len == 1){return(1)}
    else if (len == 2) {return(c(1,1))}
    else{
        fib <- numeric(len)
        fib[1] <- 1
        fib[2] <- 1
        for (i in 3:len){fib[i] <- fib[i-2] + fib[i-1]}
        return(fib)
    }

}
fibonacci(20)
```

## Exercise 10.3

```{r}
in.between <- function(x){
    if( (x <= 1) & (x >= 0) ){
        return(1)
    }
    return(0)
}
```

## Exercise 10.4

```{r}
sapply(c(-9,-0.1,0,0.1,1),in.between)
```

## Exercise 10.5

```{r}
head(letters,10)
tail(LETTERS,10)
LETTERS[22:24]
```

## Exercise 10.6

```{r}
for(n in seq(100)){
    if (n %% 3 == 0) {
        if (n %% 5 == 0){
            cat(n," FizzBuzz\n")
        } else {cat(n," Fizz\n")}
    }
    if (n %% 5 == 0 & n %% 3 != 0) {
        cat(n," Buzz\n")
    }
}
```

## Exercise 10.7

```{r}
string <- "here is an example of an unordinary sentence."
updated.string <- unlist(strsplit(tolower(string)," "))

unique(updated.string)

```

```{r}
new.vec <- c(1,2,3,4,5,7,3,2)
unique(new.vec)

```
